### ISSUE TITLE
Label On TopBar Screwed Up

### ISSUE THREAD

**Issue by levysj** [Kn1g475/SealTeam6#1]
The Label on the TopBar pushes the submit button off the screen.
![issues](https://cloud.githubusercontent.com/assets/17441684/14399032/1b0d52a2-fdb7-11e5-9573-aaf85e9d0c6b.PNG)

**Comment by levysj** [comment]
![issues2](https://cloud.githubusercontent.com/assets/17441684/14433854/060d7606-ffde-11e5-90e0-048b10b0029c.PNG)
Found this too

**Comment by patternr** [comment]
I FIXED IT
