### ISSUE TITLE
I broke the class info page

### ISSUE THREAD

**Issue by patternr** [Kn1g475/SealTeam6#14]
I added my file, checked my classes in the .txt prof, and then I removed one of my classes(CSE 102 A) in schedule and added a new class(CSE 102 D). When i did that, the info page on the report kept that class and added the other class.

[patternrComputer Science.txt](https://github.com/Kn1g475/SealTeam6/files/230752/patternrComputer.Science.txt)

**Comment by levysj** [comment]
Just patched, pull and try again.
