### ISSUE TITLE
File Labeling

### ISSUE THREAD

**Issue by patternr** [Kn1g475/SealTeam6#15]
I clicked Upload, selected a file, clicked OK, and the file name showed up. No problem. Then I immediately clicked upload again, and clicked cancel and this appeared. The error message is overlapping the file name. I could not figure it out. Thanks

![screen shot 2016-04-28 at 1 45 51 pm](https://cloud.githubusercontent.com/assets/17010015/14895673/c7cce576-0d47-11e6-8163-a7a7d9143b33.png)

**Comment by levysj** [comment]
Been Patched; Pull Latest
